### ISSUE TITLE
package not work !

### ISSUE THREAD

**Issue by lyquocnam** [Zodiase/meteor-check#1]
i tried :

```
      check(payload, Object);
      check(payload.param1, Object, ' message 1');
      check(payload.param2, Number, 'message 2');
      check(payload.param3, Object, 'message 3');
```

im using meteor 1.4.1

**Comment by Zodiase** [comment]
Could you describe exactly what is not working for you?

I have prepared a demo app here (based on Meteor 1.4.1): https://github.com/Zodiase/Meteor-Tests/tree/zodiase-check-issue-%231

The result looks perfectly fine:
![image](https://cloud.githubusercontent.com/assets/1815174/17914613/2bbebbea-6969-11e6-9d04-76d26cb78931.png)
![image](https://cloud.githubusercontent.com/assets/1815174/17914617/35f76f62-6969-11e6-92b3-1dfffa7863b7.png)

**Comment by lyquocnam** [comment]
thanks for your support !
i had not imported package yet. omg !

But in client still receive Error 500
![image](https://cloud.githubusercontent.com/assets/8347826/17915034/5a086db2-69d1-11e6-9ed8-3658a52dd6d8.png)

i make sure imported in client.
`import 'meteor/zodiase:check';`
and 
`import { check } from 'meteor/zodiase:check';`

```
// client
....
Meteor.call('test', payload, (error) => {
    console.log(error);
});
```

this only not work with meteor callback error !

i tested with check() on client & server, it worked !
additon: how to catch check error message on client ? i want show sweetalert.

so many thanks author !

**Comment by Zodiase** [comment]
https://github.com/Zodiase/meteor-check/releases/tag/v0.0.5 is out. It makes the error message consistent with the default `check`. But that doesn't grant you error details on the client side. The server side errors are hidden for a good reason: detailed error messages may expose unwanted information to the user and potentially create security issues. As a result, for server method calls, you often see `Sanitized and reported to the client as: ...`.

Now if you really do want to send the error details to the client, you have to throw a `Meteor.Error`. For example:

``` JavaScript
Meteor.methods({
  'check' (input) {
    try {
      check('foo', Number);
    } catch (err) {
      throw new Meteor.Error('Match Error', err.message);
    }
  }
});
```

Currently I don't plan to make this package support this, since this behavior goes way beyond what the default `check` does. You'd unfortunately have to capture the errors and send them to the client on your own.
